name: simpansini
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1 # <-- Baris API

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fl_chart: ^0.68.0  # Untuk grafik
  google_fonts: ^6.2.1 # Untuk font yang stylish


flutter:
  uses-material-design: true
